### PR TITLE
More best pratices for AssertJ

### PR DESCRIPTION
**Pull request by velo**
## What's changed?
1 - Created a new recipe that converts `assertThat( true ).isEqualTo( true )` to `assertThat( true ).isTrue()`, same for false
2 - added new recipe to best practices on assertJ
3 - Added ChainedAssertions for Iterator hasNext

## What's your motivation?
Noticed a lot of `isEqualTo(true)` on https://github.com/OpenFeign/querydsl/ and want to get it sorted

### Checklist
- [X] I've added unit tests to cover both positive and negative cases
- [X] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [x] I've used the IntelliJ IDEA auto-formatter on affected files

Hrmm, I'm a little short of intellij, can anyone help me out of formatting this, sorry

### CODE REVIEW

**Comment by velo** [comment]
Appretiate that, I'm having terrible connectivity issues today, trying to
download intellij for the past hour with no joy.


[image: --]

Marvin Froeder
[image: https://]about.me/velo
<https://about.me/velo?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>

**Comment by velo** [comment]
FWIW, I applied this clean to my source and got this PR from it
https://github.com/OpenFeign/querydsl/pull/493/

**Review by timtebeek — APPROVED** [review]
Great additions, thanks a lot for adding these. Like how you immediately discovered the right patterns to use to fit in with the other cases already covered. And great to see this applied to querydsl already.

Let me know if you'd like to [build recipe runs into your CI](https://www.moderne.io/blog/stop-breaking-ci-annotate-prs-with-openrewrite-recipe-fixes-as-quality-gate) to keep any such issues out going forward!

**Comment by velo** [comment]
> Let me know if you'd like to [build recipe runs into your CI](https://www.moderne.io/blog/stop-breaking-ci-annotate-prs-with-openrewrite-recipe-fixes-as-quality-gate) to keep any such issues out going forward!

Ow, that would be awesome...

I'm recurrently running AssertJCleanup and upgradetojava21 on src/test/java contents.
Right now, sources are java 11 and java 17.... so I'm not running best praticles for either, but that could be a good idea too.

I'm planning on creating a recipe for `softly.assertThat` https://github.com/assertj/assertj-examples/blob/main/assertions-examples/src/test/java/org/assertj/examples/SoftAssertionsExamples.java#L46

That would also be a massive improvement to have

**Comment by timtebeek** [comment]
Ah neat! I'd already pieced together the required steps for Maven once before here: https://github.com/langchain4j/langchain4j/pull/673
You're welcome to adopt that already in a PR if you'd want me to look that over.
You can [use preconditions](https://docs.openrewrite.org/reference/yaml-format-reference#preconditions) if you'd like to limit the recipes to certain paths only, for now.
The nice thing about having this integrated is that it fully stops new issues from trickling in.

**Comment by velo** [comment]
@timtebeek I think I missed something
https://github.com/OpenFeign/feign/pull/2479

**Comment by timtebeek** [comment]
Forgive my ignorance, but what exactly based on the link provided? I see a new test added with no immediate link to the work done here for as much as I can see in between conference sessions here.

**Comment by velo** [comment]
Sorry, I had a much more elaborated message, and seems I messed up.

I tried to follow your advice on running recipes as part of build and getting code suggestions from it.

I'm obviously missing some basic step, as I have the files from langchain4j PR, but no code suggestions.

If you have any advice, I would appreciate

Cheers

**Pull request merged**
