### PR TITLE
Add recipes for migrating Arquillian from JUnit 4 to JUnit 5.

### LINKED ISSUE #652: Add recipe for migrating Arquillian tests from JUnit 4 to JUnit 5.
## What problem are you trying to solve?

Migrating JUnit 4 Arquillian tests to JUnit 5.

## What precondition(s) should be checked before applying this recipe?

None that I'm aware of.

## Describe the situation before applying the recipe

```java
@RunWith(Arquillian.class)
class A {
    @Test
    void test() {
        // do test
    }
}
```

## Describe the situation after applying the recipe

```java
@ExtendWith(ArquillianExtension.class)
class A {
    @Test
    void test() {
        // do test
    }
}
```

## Any additional context

One difference in the best practices for the JUnit 4 to JUnit 5 migration is changing the scope of classes and methods. In some cases these tests are ran in a container. I'm not sure if this should be part of the `org.openrewrite.java.testing.junit5.JUnit5BestPractices` recipe or not yet.

## Are you interested in [contributing this recipe to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#adding-new-recipes)?
I would like to contribute or help contribute the fix. What I currently have is:
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.testing.junit5.ArquillianJUnit4ToArquillianJunit5
displayName: Use Arquillian JUnit 5 Extension
description: Migrates Arquillian `@RunWith` `Arquillian` to the JUnit Jupiter `@ExtendWith` `ArquillianExtension`.
tags:
  - testing
  - junit
  - arquillian
recipeList:
  - org.openrewrite.java.testing.junit5.RunnerToExtension:
      runners:
        - org.jboss.arquillian.junit.Arquillian
      extension: org.jboss.arquillian.junit5.ArquillianExtension
  - org.openrewrite.java.ChangePackage:
      oldPackageName: org.jboss.arquillian.junit
      newPackageName: org.jboss.arquillian.junit5
      recursive: true
  - org.openrewrite.java.dependencies.ChangeDependency:
      oldGroupId: org.jboss.arquillian.junit
      oldArtifactId: arquillian-junit-container
      newGroupId: org.jboss.arquillian.junit5
      newArtifactId: arquillian-junit5-container
  ```

### PR DESCRIPTION
**Pull request by jamezp**
## What's changed?
Add recipes for migrating Arquillian from JUnit 4 to JUnit 5

## What's your motivation?
Migrating Jakarta EE test suites from JUnit 4 to JUnit 5 when using Arquillian.

## Anything in particular you'd like reviewers to focus on?
Please ensure I'm using the correct API's and best practices for the project :)

## Have you considered any alternatives or workarounds?
The only workarounds I'm aware of would be a manual find/replace which is what I've currently been doing.

### Checklist
- [ ] I've added unit tests to cover both positive and negative cases
- [x] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [x] I've used the IntelliJ IDEA auto-formatter on affected files

- resolves #652

### CODE REVIEW

**Comment by timtebeek** [comment]
Thanks already @jamezp ! I've moved your recipes out into a separate file and added a test class for the dependency issue you had reported. Hope that helps you there. Let me know when this is ready for review by unmarking it as draft.

**Comment by jamezp** [comment]
Excellent, thank you @timtebeek! I'll run some more conversions on some other projects to look for any additional possible issues.

**Comment by jamezp** [comment]
@timtebeek I added one more change to ensure a import was done. 

I also ran it against a much larger test suite, https://github.com/wildfly/wildfly/tree/main/testsuite/integration/basic, and ran into some issues. These might just be issues with the tests themselves though. A lot of removal of exceptions from the test methods causing compile issues and changing try/catch/fail to assertThrows with non-effective final variables. 

Again, I don't think that's necessarily a bug in any of the recipes.

I also noticed it doesn't seem to handle multiple source directories well, but I also know that is an odd setup so not something I'm too concerned about

**Review by timtebeek — COMMENTED** [review]
Thanks a lot for kicking this off @jamezp ! I've changed the recipe you added to reuse JavaTemplate and ChangeType, which are more convenient than the explicit LST element constructors seen before; I've also added a test and now include your recipes in the JUnit 4 to 5 migration, such that folks get these changes applied by default. 🥳

**Review by timtebeek — APPROVED** [review]

**Comment by jamezp** [comment]
Thank you @timtebeek This is awesome!

**Pull request merged**
