### PR TITLE
Adding AssertNotEqualsToAssertThat and better message handling.

### PR DESCRIPTION
**Pull request by tkvangorder**

### CODE REVIEW

**Comment by tkvangorder** [comment]
This PR is predicated on fixes made to rewrite in this PR: https://github.com/openrewrite/rewrite/pull/106

**Comment by tkvangorder** [comment]
@sambsnyd @SofiaBrittoSchwartz This is now ready for review.

**Review by sambsnyd — APPROVED** [review]
Looks good, nice work

**Review by jkschneider — APPROVED** [review]
LGTM!

**Pull request merged**
