### PR TITLE
Convert `assertTrue(false, String)` and `assertFalse(true, String)` with `fail(String)`

### PR DESCRIPTION
**Pull request by Laurens-W**
## What's changed?

Add recipe to rewrite assertTrue(false, "message") and assertFalse(true, "message") to fail("message")

## What's your motivation?

- Fixes https://github.com/openrewrite/rewrite-testing-frameworks/issues/464

## Anything in particular you'd like reviewers to focus on?

Test coverage

## Anyone you would like to review specifically?

@timtebeek @timo-abele 

### Checklist
- [x] I've added unit tests to cover both positive and negative cases
- [x] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [x] I've used the IntelliJ IDEA auto-formatter on affected files

### CODE REVIEW

**Comment by timtebeek** [comment]
Awesome start, thanks! Did you notice this comment in the issue?

> We could even implement this as a Refaster recipe, similar to what we recently added to rewrite-static-analysis in
> https://github.com/openrewrite/rewrite-static-analysis/pull/231

I think we can keep the tests, and replace the recipes with just a couple lines in Refaster recipes.

**Comment by Laurens-W** [comment]
> Awesome start, thanks! Did you notice this comment in the issue?
> 
> > We could even implement this as a Refaster recipe, similar to what we recently added to rewrite-static-analysis in
> > [openrewrite/rewrite-static-analysis#231](https://github.com/openrewrite/rewrite-static-analysis/pull/231)
> 
> I think we can keep the tests, and replace the recipes with just a couple lines in Refaster recipes.

Must admit I skimmed over that part :) I will continue working on this next week and apply the proposed changes!

**Review by timtebeek — CHANGES_REQUESTED** [review]
Great to see! Let's merge the two separate test classes into a single `AssertLiteralBooleanToFailRecipeTest`, and within those I think we write a single test that covers all four cases from a single unit test that just has the four statements in one.

**Review by timtebeek — APPROVED** [review]
Neat addition; thanks @Laurens-W !

**Pull request merged**
