### PR TITLE
Improvement of Replace PowerMockito with Mockito static mocking

### PR DESCRIPTION
**Pull request by klauerm**
Fixes https://github.com/openrewrite/rewrite-testing-frameworks/issues/293

### CODE REVIEW

**Comment by klauerm** [comment]
Hi @sambsnyd @timtebeek,
Can you have a look. The integration test src/test/java/org/openrewrite/java/testing/mockito/ReplacePowerMockitoIntegrationTest.java holds all the requirement we need for our code base. But it is still failing. I don't know how to fix the issue I mentioned in [slack](https://rewriteoss.slack.com/archives/C01A843MWG5/p1675949738405979)

**Comment by klauerm** [comment]
@timtebeek  I've fixed all tests except for 1 in src/test/java/org/openrewrite/java/testing/mockito/ReplacePowerMockitoIntegrationTest.java
Here the feature for using testng annotations, if the mockito tests are written with testng is still missng. Can you please activate this integration test for the pipeline again?
Thank you, Matthias

**Comment by timtebeek** [comment]
As discussed on Slack
> ReplacePowerMockitoIntegrationTest > testThatPowerMockitoIsReplacedInTestNGTests() FAILED
> it seems to use `@AfterEach` instead of `@AfterMethod`
> I think [the `maybeAddTearDownMethodBody` function](https://github.com/klauerm/rewrite-testing-frameworks/blob/feature/replace-power-mockito-recipe/src/main/java/org/openrewrite/java/testing/mockito/PowerMockitoMockStaticToMockito.java#L168) either needs to be aware of TestNG, and then add the corresponding AfterEach/AfterMethod annotation, or needs a twin to handle TestNG tear down.. now it seems specific to JUnit, and I'm not seeing an equivalent for TestNG

**Comment by sambsnyd** [comment]
I haven't reviewed this in great detail, so there may be suggestions or improvements to come later, but for now we can merge and iterate on it

**Pull request merged**
