### PR TITLE
Strip test_ prefix from snake cased methods

### PR DESCRIPTION
**Pull request by timtebeek**
Small addition after exposure to new code base.

### CODE REVIEW

**Comment by timtebeek** [comment]
Failure seems unrelated:
> JUnitAssertTrueToAssertThatTest > singleStaticMethodNoMessage() FAILED

**Comment by pway99** [comment]
Thanks @timtebeek, 
I added another check to prevent renaming a method if there is another method having the same name as the new name. 
feb241ae86230232b64a3dd00131f63779cdeb67

**Comment by timtebeek** [comment]
Ah perfect, thanks! That's one of the issues I ran into as well; good to have that covered.

**Comment by pway99** [comment]
Thanks for your effort to keep improving this one :)

**Pull request merged**
