### PR TITLE
Recipe to simplify assertions on Optionals

### LINKED ISSUE #466: `assertThat(anOptional.isPresent()).isTrue()` should be converted to `assertThat(anOptional).isPresent()`
## What problem are you trying to solve?

In my codebase I have almost every combination of:
`assertThat(anOptional.isEmpty()).isFalse()`
`assertThat(anOptional.isEmpty()).isTrue()`
`assertThat(anOptional.isPresent()).isFalse()`
`assertThat(anOptional.isPresent()).isTrue()`

## Describe the solution you'd like

They should be converted to `assertThat(anOptional).isPresent()` and `assertThat(anOptional).isEmpty()`.

## Are you interested in [contributing this feature to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#new-features)?

no

### PR DESCRIPTION
**Pull request by timo-abele**
## What's changed?

Adds first refaster recipe

## What's your motivation?

fix #466
### Checklist
- [ ] I've added unit tests to cover both positive and negative cases
- [ ] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [ ] I've used the IntelliJ IDEA auto-formatter on affected files

### CODE REVIEW

**Comment by timtebeek** [comment]
Thanks for getting this started! As indicated in Slack as well we have two small hurdles to cross here before we can merge this in

1. support for generic over in https://github.com/openrewrite/rewrite-templating
2. allowing Java 9+ features in refaster recipes with something similar to
   - https://github.com/openrewrite/rewrite-migrate-java/pull/399
   - https://github.com/openrewrite/rewrite-templating/pulls

We're very near with all of those, so we can keep this PR open and return to it once we're ready.

**Comment by timtebeek** [comment]
I'm guessing this has since been surpassed by 
- https://github.com/openrewrite/rewrite-testing-frameworks/pull/474 ?

If so we can close this one.

Thanks though! Good attempt if we were just a tad further with rewrite-templating such that generated recipes are safe to run on Java 8.

**Comment by timo-abele** [comment]
> I'm guessing this has since been surpassed by
> 
>     * [Add more simplifications #474](https://github.com/openrewrite/rewrite-testing-frameworks/pull/474) ?
> 
> 
> If so we can close this one.
> 
> Thanks though! Good attempt if we were just a tad further with rewrite-templating such that generated recipes are safe to run on Java 8.

In terms of functionality this PR is obsolete. Once the blockers are resolved, rewriting the recipes currently covered by `SimplifyChainedAssertJAssertion` into refaster recipes would make the code more readable. Then, the code written here could be reused. But it wouldn't be much effort to write it anew either...

**Comment by timtebeek** [comment]
I'm leaning towards closing this one at least for now then, as we have some blockers to sort first, and even then there might be performance challenges to solve before we rewrite more recipes to Refaster style (as much as I like that option!).

**Pull request closed without merging**
