### PR TITLE
Add dependency on JUnit Jupiter (Aggregator) only, not api + engine

### PR DESCRIPTION
**Pull request by timtebeek**
[As suggested here](https://github.com/apache/maven-wrapper/pull/61#pullrequestreview-1084485426).

### CODE REVIEW

**Comment by timtebeek** [comment]
The test failures are... interesting 🤔,
especially given the minimal change set.

**Comment by timtebeek** [comment]
Ah the test failures are on master as well after https://github.com/openrewrite/rewrite-testing-frameworks/commit/d0ce18dd3da45fbcd82e178f8ef9ee6b9d5ba2c9 ; will wait for a fix to those & merge main when done.

It seems [org.junit.jupiter/junit-jupiter](https://search.maven.org/artifact/org.junit.jupiter/junit-jupiter) has been around since 5.4.0 from Feb 2019;
With the [current dependencies added in Nov 2020 originally](https://github.com/openrewrite/rewrite-testing-frameworks/commit/9b2b6e29c3c05f981096f656c4d9c75118b012a7);
not immediately clear why those where chosen back then.

**Comment by timtebeek** [comment]
Might even want to remove the previous two separate dependencies are replace those with this singular one, to also update projects that have already migrated.

**Review by tkvangorder — APPROVED** [review]
Thank you!

**Pull request merged**
