### PR TITLE
`JUnitAssertEqualsToAssertThat` skipped adding `assertThat` import for custom classes

### PR DESCRIPTION
**Pull request by timo-abele**
## What's your motivation?

fixing #479 

### Checklist
- [ ] I've added unit tests to cover both positive and negative cases
- [ ] I've read and applied the [recipe conventions and best practices](https://docs.openrewrite.org/authoring-recipes/recipe-conventions-and-best-practices)
- [ ] I've used the IntelliJ IDEA auto-formatter on affected files

### CODE REVIEW

**Review by timtebeek — APPROVED** [review]
Yes perfect! I've pushed up a small polishing commit, and added a clarifying comment just in case this pops up in the future. Thanks again!

**Comment by philippe-granet** [comment]
@timtebeek Since this commit: https://github.com/openrewrite/rewrite-testing-frameworks/pull/480/commits/f11cb717bc5c408c8230cfea5363b5cf7809906a , execution of this recipe is dramaticaly slow down.
Removing `assertionsParser` cache is required to fix https://github.com/openrewrite/rewrite-testing-frameworks/issues/479?

**Comment by timtebeek** [comment]
Hi @philippe-granet , thanks for calling that out! I've been traveling for a couple weeks, with a few more to go, so I'm tagging @knutwannheden to see if he can have a look before I'm back.

**Comment by philippe-granet** [comment]
> Hi @philippe-granet , thanks for calling that out! I've been traveling for a couple weeks, with a few more to go, so I'm tagging @knutwannheden to see if he can have a look before I'm back.

Finaly, the problem came from this commit: https://github.com/openrewrite/rewrite-testing-frameworks/commit/368384a174bd92d49880c19a879fb9e14afcfa27  
Calling `.contextSensitive()` remove JavaTemplate cache and it really slow down recipes.

**Comment by philippe-granet** [comment]
> > Hi @philippe-granet , thanks for calling that out! I've been traveling for a couple weeks, with a few more to go, so I'm tagging @knutwannheden to see if he can have a look before I'm back.
> 
> Finaly, the problem came from this commit: [368384a](https://github.com/openrewrite/rewrite-testing-frameworks/commit/368384a174bd92d49880c19a879fb9e14afcfa27) Calling `.contextSensitive()` remove JavaTemplate cache and it really slow down recipes.

I made a PR to fix this problem: https://github.com/openrewrite/rewrite-testing-frameworks/pull/505

**Pull request merged**
