### PR TITLE
Only add `hamcrest-junit` dependency when using `assertThat` or `assumeThat`

### PR DESCRIPTION
**Pull request by FieteO**
## What's changed?

Remove the `hamcrest-junit` dependency when running the `JUnit4to5Migration` recipe.

## What's your motivation?

The dependency is not needed in the Junit 5 context (AFAIK)

### CODE REVIEW

**Comment by timtebeek** [comment]
How does this interact with this recipe a little further up/down? As we seem to add that explicitly in a JUnit 5 upgrade
https://github.com/openrewrite/rewrite-testing-frameworks/blob/b7d3b84556a165c07e3aa5e5bb71382beeda1eac/src/main/resources/META-INF/rewrite/junit5.yml#L92
https://github.com/openrewrite/rewrite-testing-frameworks/blob/b7d3b84556a165c07e3aa5e5bb71382beeda1eac/src/main/resources/META-INF/rewrite/junit5.yml#L166-L172

What makes that the dependency is not or no longer needed in your case?

**Comment by FieteO** [comment]
Hmm, you are right. Probably some more investigation is needed as to when the dependency is needed/when it can be removed.
The `hamcrest-junit` seems to have been [the result of decoupling the the Hamcrest portions in Junit 4 into a separate dependency](https://github.com/hamcrest/JavaHamcrest/issues/92).
This dependency hasn't received an update since 9 years and it's hard to say what use it serves. The PR that added it to the `junit5.yml` was titled `Migrate JUnit 4 `Assume#assumeThat()` to `hamcrest-junit`` to fix issue #327 .

As far as I can tell, Junit 5 [also has support for Assumptions](https://junit.org/junit5/docs/5.0.0/api/org/junit/jupiter/api/Assumptions.html).
Maybe @knutwannheden can comment on this?

**Comment by timtebeek** [comment]
This was a fun one @FieteO ; thanks for raising this for visibility. Turns out we were a little too eager adding that `hamcrest-junit` dependency on _any_ use of `org.junit.Assume`, as opposed to only when using `assertThat` or `assumeThat`. Solved now by creating a new scanning recipe that looks at methods in use and only if found adds the dependency.

**Review by timtebeek — APPROVED** [review]
Ended up removing the declarative `AddDependency` that was there before, and implementing a scanning recipe that's a little more selective. Thanks again for calling out this issue with over eager dependency addition!

**Comment by FieteO** [comment]
Great, that there indeed was something to improve here. Thanks @timtebeek for working on this.

**Pull request merged**
