### PR TITLE
Mockito 4

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by jkschneider** [comment]
These particular dependencies need to be pinned to 3 because we are testing Mockito 2 to 3 changes, but you make me wonder now what breaking changes there are between Mockito 3 and 4!

**Comment by jkschneider** [comment]
Maybe it helps to add more context. In `rewrite-spring` we have a [similar scenario](https://github.com/openrewrite/rewrite-spring/blob/main/build.gradle.kts#L212-L228) and actually create whole dependency configurations to isolate changes from one minor release to another. Then we can group the unit tests for say Mockito 2->3 in one source set that depends on Mockito 2 (the beginning state of a test to Mockito 3), and another source set that depends on Mockito 3 (the beginning state of a test to Mockito 4)

**Comment by pway99** [comment]
added a issue https://github.com/openrewrite/rewrite-testing-frameworks/issues/186 for tracking the mockito 3 to 4 migration

**Comment by tkvangorder** [comment]
Closing this as we are tracking the mockito 4 with #186

**Pull request closed without merging**
